name: GitHub Archive

on:
  push:
  
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: dist/
          dest: result.zip
      - name: Upload to relase
        uses: svenstaro/upload-release-action@v2
        with:
          file: result.zip
          asset_name: result.zip
          overwrite: true
          body: "This is my release text"
