name: GitHub Archive

on:
  push:
  
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: darshitsri/zip-release@v3
        with:
          filename: result.zip
      - name: Upload to relase
        uses: svenstaro/upload-release-action@v2
        with:
          file: result.zip
          asset_name: release.zip
          overwrite: true
          body: "This is my release text"
